services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "0.0.0.0:15672:15672"
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:1883:1883"
      - "0.0.0.0:15675:15675"
    env_file:
      - ./.env

  web:
    build: ./web
    container_name: web
    restart: always
    hostname: web
    ports:
      - "0.0.0.0:8555:8555"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8555"]
    volumes:
      - ./web:/app
    env_file:
      - ./.env

  db:
    image: postgres:15.0
    restart: always
    container_name: db
    hostname: db
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
