services:
  postgres:
    image: postgres:15.0
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5433:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  web:
    build: ./web
    container_name: web
    restart: always
    hostname: web
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./web:/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
      - "15675:15675"
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres-data:
  pgadmin-data:
