services:
  postgres:
    image: postgres:15.0
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  web:
    build: ./web
    image: web
    container_name: web
    hostname: web
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./web:/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  rabbitmq:
    build: ./rabbitmq
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
      - "5672:5672"
      - "1884:1883"
      - "15675:15675"
    env_file:
      - ./.env
    depends_on:
      - web

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

volumes:
  postgres_data:
  pgadmin_data:
